-- 1. Criar a tabela de pastas
CREATE TABLE IF NOT EXISTS public.folders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  emoji text DEFAULT '📁'
);

-- 2. Habilitar segurança (RLS)
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;

-- 3. Criar políticas de acesso (apenas o dono pode ver/editar suas pastas)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can see their own folders') THEN
    CREATE POLICY "Users can see their own folders" ON public.folders
      FOR SELECT USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can create their own folders') THEN
    CREATE POLICY "Users can create their own folders" ON public.folders
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update their own folders') THEN
    CREATE POLICY "Users can update their own folders" ON public.folders
      FOR UPDATE USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can delete their own folders') THEN
    CREATE POLICY "Users can delete their own folders" ON public.folders
      FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;

-- 4. Adicionar a coluna de vínculo na tabela de formulários (se não existir)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='forms' AND column_name='folder_id') THEN
    ALTER TABLE public.forms ADD COLUMN folder_id bigint REFERENCES public.folders(id) ON DELETE SET NULL;
  END IF;
END $$;
